#! /usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

random-wallpaper
xxkb &
dunst &
lxqt-policykit-agent &
xcape -e 'Super_R=Super_R|X;Super_L=Super_L|X'

pkill polybar
echo "---" | tee -a ~/.cache/polybar-top.log ~/.cache/polybar-bottom.log
polybar desktop-top >>~/.cache/polybar-top.log 2>&1 &
polybar desktop-bottom >>~/.cache/polybar-bottom.log 2>&1 &
