#! /usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

random-wallpaper
xxkb &
dunst &
lxqt-policykit-agent &
xcape -e 'Super_R=Super_R|X;Super_L=Super_L|X'

alacritty -e fish -c "cd ~/code/fitlog-phoenix/ && mix phx.server" &
alacritty -e fish -c "cd ~/code/fitlog-vue/ && npm run dev" &

pkill polybar
echo "---" | tee -a ~/.cache/polybar-top.log ~/.cache/polybar-bottom.log
polybar top >>~/.cache/polybar-top.log 2>&1 &
polybar bottom >>~/.cache/polybar-bottom.log 2>&1 &
